[package]
name = "find_unicode"
default-run="fu"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]
edition = "2018"

[dependencies]
skim = "0.6.8"

[[bin]]
name = "fu"
path = "src/main.rs"

[[bin]]
name = "gen_data"
path = "src/gen_data.rs"
